export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REQUEST_AUTH_DATA = 'REQUEST_AUTH_DATA';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REQUEST_POST_DATA = 'REQUEST_POST_DATA';
export const REQUEST_IMAGE_DATA = 'REQUEST_IMAGE_DATA';
export const POST_CREATION_SUCCESS = 'POST_CREATION_SUCCESS';
export const POST_CREATION_FAIL = 'POST_CREATION_FAIL';
export const RECEIVE_POSTS = 'RECEIVE_ALL_POSTS';
export const RECEIVE_USER_POSTS = 'RECEIVE_USER_POSTS';
export const RECEIVE_SINGLE_POST = 'RECEIVE_SINGLE_POST';
export const POSTS_FETCHING_ERROR = 'POSTS_FETCHING_ERROR';
export const USER_POSTS_FETCHING_ERROR = 'USER_POSTS_FETCHING_ERROR';
export const SINGLE_POST_FETCHING_ERROR = 'SINGLE_POST_FETCHING_ERROR';
export const POST_DELETE_FINISHED = 'POST_DELETE_FINISHED';
export const COMMENT_HANDLING_FAIL = 'COMMENT_HANDLING_FAIL';
export const IMAGE_HANDLING_FINISHED = 'IMAGE_HANDLING_FINISHED';

export const REQUEST_PROFILE_DATA = 'REQUEST_PROFILE_DATA';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const PROFILE_UPDATE_FINISHED = 'PROFILE_UPDATE_FINISHED';
export const PROFILE_DELETE_FINISHED = 'PROFILE_DELETE_FINISHED';
export const FOLLOW_HANDLING_FINISHED = 'FOLLOW_HANDLING_FINISHED';
export const PROFILE_FETCHING_ERROR = 'PROFILE_FETCHING_ERROR';